### ISSUE TITLE
Version 2.9.1

### ISSUE THREAD

**Issue by Anatl** [AdaskoTheBeAsT/Typewriter#17] opened 2022-09-11 13:00 UTC
Hello,

We have an issue with the installation.  Please help us figure it out :)
TypeWriter version 2.9.1 for Visual Studio 2022 V17.3.2.

In one computer the installation was succsesfull. In a different computer we get the following error:
![image](https://user-images.githubusercontent.com/8081196/189528760-fdf8a57e-367b-4075-b4b8-f950e6b81e9d.png)
(The extention is not installable on any currently installed products)

And the following is frrom the log file:
11-Sep-22 1:44:29 PM - Microsoft VSIX Installer
11-Sep-22 1:44:29 PM - -------------------------------------------
11-Sep-22 1:44:29 PM - vsixinstaller.exe version:
11-Sep-22 1:44:29 PM - 17.3.2092
11-Sep-22 1:44:29 PM - -------------------------------------------
11-Sep-22 1:44:29 PM - Command line parameters:
11-Sep-22 1:44:29 PM - C:\Program Files (x86)\Microsoft Visual Studio\Installer\resources\app\ServiceHub\Services\Microsoft.VisualStudio.Setup.Service\VSIXInstaller.exe,C:\Users\zoe.eliraz\Downloads\Typewriter.vsix
11-Sep-22 1:44:29 PM - -------------------------------------------
11-Sep-22 1:44:29 PM - Microsoft VSIX Installer
11-Sep-22 1:44:29 PM - -------------------------------------------
11-Sep-22 1:44:29 PM - Skipping product Microsoft.VisualStudio.Product.BuildTools (429bceb9) since it does not support extensions
11-Sep-22 1:44:29 PM - Initializing Install...
11-Sep-22 1:44:29 PM - Extension Details...
11-Sep-22 1:44:29 PM -     Identifier         : 68E244F1-14E1-4681-A51C-5B902B9EE96C
11-Sep-22 1:44:29 PM -     Name               : Typewriter64
11-Sep-22 1:44:29 PM -     Author             : frhagn
11-Sep-22 1:44:29 PM -     Version            : 2.3.0
11-Sep-22 1:44:29 PM -     Description        : Typewriter generates TypeScript files from c# code files using TypeScript Templates. This allows you to create fully typed TypeScript representations of server side API that automatically updates when you make changes to your c# code.
11-Sep-22 1:44:29 PM -     Locale             : en-US
11-Sep-22 1:44:29 PM -     MoreInfoURL        : http://frhagn.github.io/Typewriter/
11-Sep-22 1:44:29 PM -     InstalledByMSI     : False
11-Sep-22 1:44:29 PM -     SupportedFrameworkVersionRange : [4.7.2,)
11-Sep-22 1:44:29 PM -
11-Sep-22 1:44:29 PM -     SignatureState     : Unsigned
11-Sep-22 1:44:29 PM -     Supported Products :
11-Sep-22 1:44:29 PM -         Microsoft.VisualStudio.Community
11-Sep-22 1:44:29 PM -             Version : [17.0,18.0)
11-Sep-22 1:44:29 PM -             ProductArchitecture : amd64
11-Sep-22 1:44:29 PM -         Microsoft.VisualStudio.Pro
11-Sep-22 1:44:29 PM -             Version : [17.0,18.0)
11-Sep-22 1:44:29 PM -             ProductArchitecture : amd64
11-Sep-22 1:44:29 PM -         Microsoft.VisualStudio.Enterprise
11-Sep-22 1:44:29 PM -             Version : [17.0,18.0)
11-Sep-22 1:44:29 PM -             ProductArchitecture : amd64
11-Sep-22 1:44:29 PM -
11-Sep-22 1:44:29 PM -     References         :
11-Sep-22 1:44:29 PM -     Prerequisites      :
11-Sep-22 1:44:29 PM -         -------------------------------------------------------
11-Sep-22 1:44:29 PM -         Identifier   : Microsoft.VisualStudio.Component.CoreEditor
11-Sep-22 1:44:29 PM -         Name         : Visual Studio core editor
11-Sep-22 1:44:29 PM -         Version      : [17.0,18.0)
11-Sep-22 1:44:29 PM -
11-Sep-22 1:44:29 PM - Signature Details...
11-Sep-22 1:44:29 PM -     Extension is not signed.
11-Sep-22 1:44:29 PM -
11-Sep-22 1:44:29 PM - Searching for applicable products...
11-Sep-22 1:44:29 PM - Found installed product - Microsoft Visual Studio Professional 2013
11-Sep-22 1:44:29 PM - Found installed product - Microsoft Visual Studio 2013 Shell (Integrated)
11-Sep-22 1:44:29 PM - Found installed product - Global Location
11-Sep-22 1:44:29 PM - Found installed product - Visual Studio Enterprise 2022
11-Sep-22 1:44:30 PM - System.InvalidOperationException: VSHiveStub.exe failed: Unknown error
   at VSIXInstaller.LocationBasedSKU.SettingsManagerData.get_RegRootHiveOverride()
   at VSIXInstaller.LocationBasedSKU.get_RegRootHiveOverride()
   at VSIXInstaller.SupportedVSSKU.InitializeSettingsManager()
   at VSIXInstaller.SupportedVSSKU.get_Host()
   at VSIXInstaller.ExtensionEngineFactoryForSku.GetEngineForSku(SupportedVSSKU sku)
   at VSIXInstaller.SupportedVSSKU.CreateExtensionEngine()
   at System.Lazy`1.CreateValue()
   at System.Lazy`1.LazyInitValue()
   at System.Lazy`1.get_Value()
   at VSIXInstaller.ExtensionService.GetExtensionEngineForApplicableSKU(ICommandLineData cmdLineData, SupportedVSSKU supportedSKU, IInstallableExtension installableExtension, List`1 applicableSKUs, Boolean isRepairSupported)
   at VSIXInstaller.ExtensionService.TryAddSkuToValidSkuList(ICommandLineData cmdLineData, SupportedVSSKU supportedSKU, IInstallableExtension extension, List`1 validSKUs, Boolean isRepairSupported)
11-Sep-22 1:44:30 PM - Found installed product - Visual Studio Professional 2017
11-Sep-22 1:44:30 PM - Found installed product - Visual Studio Enterprise 2019 (2)
11-Sep-22 1:44:30 PM - Found installed product - Visual Studio Professional 2019
11-Sep-22 1:44:30 PM - VSIXInstaller.NoApplicableSKUsException: This extension is not installable on any currently installed products.
   at VSIXInstaller.ExtensionService.GetInstallableDataImpl(IInstallableExtension extension, String extensionPackParentName, Boolean isRepairSupported, IStateData stateData, IEnumerable`1& skuData)
   at VSIXInstaller.ExtensionService.GetInstallableData(String vsixPath, String extensionPackParentName, Boolean isRepairSupported, IStateData stateData, IEnumerable`1& skuData)
   at VSIXInstaller.ExtensionPackService.IsExtensionPack(IStateData stateData, Boolean isRepairSupported)
   at VSIXInstaller.ExtensionPackService.ExpandExtensionPackToInstall(IStateData stateData, Boolean isRepairSupported)
   at VSIXInstaller.App.Initialize(Boolean isRepairSupported)
   at VSIXInstaller.App.Initialize()
   at System.Threading.Tasks.Task`1.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()

Thank you!!

**Comment by AdaskoTheBeAsT** [comment] 2022-09-11 17:04
hi,

coul you please uninstall extension completely and install it one more time (also latest update to VS2022?)

**Comment by Anatl** [comment] 2022-09-11 17:07
Hi,

Thank you for the quick reply!
What do you mean touninstall extension completely?
I could not install it at all.

קבל ‏Outlook עבור Android‏<https://aka.ms/AAb9ysg>
________________________________

**Comment by AdaskoTheBeAsT** [comment] 2022-09-11 17:10
ok I would try first with updating VS to latest version - based on log it seems that you have multiple VS installed - not sure how it influence installation

**Comment by Anatl** [comment] 2022-09-11 17:16
Yes, also VS 2013, 2017 and 2019 install on the computer.
But as I said in my original question, we have another computer also with multiple visual studio versions that the installation was successful.

קבל ‏Outlook עבור Android‏<https://aka.ms/AAb9ysg>
________________________________

**Comment by AdaskoTheBeAsT** [comment] 2022-09-11 17:18
so it is more machine related then setup related - did you try repair installation of vs2022 and then install extension?

**Comment by Anatl** [comment] 2022-09-11 17:20
Yes I did a repair installation

קבל ‏Outlook עבור Android‏<https://aka.ms/AAb9ysg>
________________________________

**Comment by AdaskoTheBeAsT** [comment] 2022-09-11 17:23
can you update to 17.3.3 and then install extension in v2.9.2?

**Comment by Anatl** [comment] 2022-09-11 17:25
I will try and update you.
Thank you

קבל ‏Outlook עבור Android‏<https://aka.ms/AAb9ysg>
________________________________

**Comment by Anatl** [comment] 2022-09-12 07:42
still getting an error:

12-Sep-22 9:45:18 AM - Microsoft VSIX Installer
12-Sep-22 9:45:18 AM - -------------------------------------------
12-Sep-22 9:45:18 AM - vsixinstaller.exe version:
12-Sep-22 9:45:18 AM - 17.3.2092
12-Sep-22 9:45:18 AM - -------------------------------------------
12-Sep-22 9:45:18 AM - Command line parameters:
12-Sep-22 9:45:18 AM - C:\Program Files (x86)\Microsoft Visual Studio\Installer\resources\app\ServiceHub\Services\Microsoft.VisualStudio.Setup.Service\VSIXInstaller.exe,C:\Users\zoe.eliraz\Downloads\Typewriter (4).vsix
12-Sep-22 9:45:18 AM - -------------------------------------------
12-Sep-22 9:45:18 AM - Microsoft VSIX Installer
12-Sep-22 9:45:18 AM - -------------------------------------------
12-Sep-22 9:45:18 AM - Skipping product Microsoft.VisualStudio.Product.BuildTools (429bceb9) since it does not support extensions
12-Sep-22 9:45:19 AM - Initializing Install...
12-Sep-22 9:45:19 AM - Extension Details...
12-Sep-22 9:45:19 AM -     Identifier         : 68E244F1-14E1-4681-A51C-5B902B9EE96C
12-Sep-22 9:45:19 AM -     Name               : Typewriter64
12-Sep-22 9:45:19 AM -     Author             : frhagn
12-Sep-22 9:45:19 AM -     Version            : 2.9.2
12-Sep-22 9:45:19 AM -     Description        : Typewriter generates TypeScript files from c# code files using TypeScript Templates. This allows you to create fully typed TypeScript representations of server side API that automatically updates when you make changes to your c# code.
12-Sep-22 9:45:19 AM -     Locale             : en-US
12-Sep-22 9:45:19 AM -     MoreInfoURL        : http://frhagn.github.io/Typewriter/
12-Sep-22 9:45:19 AM -     InstalledByMSI     : False
12-Sep-22 9:45:19 AM -     SupportedFrameworkVersionRange : [4.7.2,)
12-Sep-22 9:45:19 AM -
12-Sep-22 9:45:19 AM -     SignatureState     : Unsigned
12-Sep-22 9:45:19 AM -     Supported Products :
12-Sep-22 9:45:19 AM -         Microsoft.VisualStudio.Community
12-Sep-22 9:45:19 AM -             Version : [17.3.3,18.0)
12-Sep-22 9:45:19 AM -             ProductArchitecture : amd64
12-Sep-22 9:45:19 AM -         Microsoft.VisualStudio.Pro
12-Sep-22 9:45:19 AM -             Version : [17.3.3,18.0)
12-Sep-22 9:45:19 AM -             ProductArchitecture : amd64
12-Sep-22 9:45:19 AM -         Microsoft.VisualStudio.Enterprise
12-Sep-22 9:45:19 AM -             Version : [17.3.3,18.0)
12-Sep-22 9:45:19 AM -             ProductArchitecture : amd64
12-Sep-22 9:45:19 AM -
12-Sep-22 9:45:19 AM -     References         :
12-Sep-22 9:45:19 AM -     Prerequisites      :
12-Sep-22 9:45:19 AM -         -------------------------------------------------------
12-Sep-22 9:45:19 AM -         Identifier   : Microsoft.VisualStudio.Component.CoreEditor
12-Sep-22 9:45:19 AM -         Name         : Visual Studio core editor
12-Sep-22 9:45:19 AM -         Version      : [17.3.3,18.0)
12-Sep-22 9:45:19 AM -
12-Sep-22 9:45:19 AM - Signature Details...
12-Sep-22 9:45:19 AM -     Extension is not signed.
12-Sep-22 9:45:19 AM -
12-Sep-22 9:45:19 AM - Searching for applicable products...
12-Sep-22 9:45:19 AM - Found installed product - Microsoft Visual Studio Professional 2013
12-Sep-22 9:45:19 AM - Found installed product - Microsoft Visual Studio 2013 Shell (Integrated)
12-Sep-22 9:45:19 AM - Found installed product - Global Location
12-Sep-22 9:45:19 AM - Found installed product - Visual Studio Enterprise 2022
12-Sep-22 9:45:19 AM - System.InvalidOperationException: VSHiveStub.exe failed: Unknown error
   at VSIXInstaller.LocationBasedSKU.SettingsManagerData.get_RegRootHiveOverride()
   at VSIXInstaller.LocationBasedSKU.get_RegRootHiveOverride()
   at VSIXInstaller.SupportedVSSKU.InitializeSettingsManager()
   at VSIXInstaller.SupportedVSSKU.get_Host()
   at VSIXInstaller.ExtensionEngineFactoryForSku.GetEngineForSku(SupportedVSSKU sku)
   at VSIXInstaller.SupportedVSSKU.CreateExtensionEngine()
   at System.Lazy`1.CreateValue()
   at System.Lazy`1.LazyInitValue()
   at System.Lazy`1.get_Value()
   at VSIXInstaller.ExtensionService.GetExtensionEngineForApplicableSKU(ICommandLineData cmdLineData, SupportedVSSKU supportedSKU, IInstallableExtension installableExtension, List`1 applicableSKUs, Boolean isRepairSupported)
   at VSIXInstaller.ExtensionService.TryAddSkuToValidSkuList(ICommandLineData cmdLineData, SupportedVSSKU supportedSKU, IInstallableExtension extension, List`1 validSKUs, Boolean isRepairSupported)
12-Sep-22 9:45:19 AM - Found installed product - Visual Studio Professional 2017
12-Sep-22 9:45:19 AM - Found installed product - Visual Studio Enterprise 2019 (2)
12-Sep-22 9:45:19 AM - Found installed product - Visual Studio Professional 2019
12-Sep-22 9:45:19 AM - VSIXInstaller.NoApplicableSKUsException: This extension is not installable on any currently installed products.
   at VSIXInstaller.ExtensionService.GetInstallableDataImpl(IInstallableExtension extension, String extensionPackParentName, Boolean isRepairSupported, IStateData stateData, IEnumerable`1& skuData)
   at VSIXInstaller.ExtensionService.GetInstallableData(String vsixPath, String extensionPackParentName, Boolean isRepairSupported, IStateData stateData, IEnumerable`1& skuData)
   at VSIXInstaller.ExtensionPackService.IsExtensionPack(IStateData stateData, Boolean isRepairSupported)
   at VSIXInstaller.ExtensionPackService.ExpandExtensionPackToInstall(IStateData stateData, Boolean isRepairSupported)
   at VSIXInstaller.App.Initialize(Boolean isRepairSupported)
   at VSIXInstaller.App.Initialize()
   at System.Threading.Tasks.Task`1.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()

**Comment by Anatl** [comment] 2022-11-07 11:24
we still get the error above.
do you have any idea what is wrong?

**Comment by AdaskoTheBeAsT** [comment] 2023-12-15 20:29
The error log you've provided indicates a few potential issues that might be causing the problem when installing a VSIX extension in Visual Studio. Here's a breakdown of the key points and their possible root causes:

System.InvalidOperationException: VSHiveStub.exe failed: Unknown error

This error suggests that there's an issue with the Visual Studio environment. VSHiveStub.exe is a utility used by Visual Studio, and an "Unknown error" could be due to a variety of reasons including corrupted Visual Studio installation, issues with user permissions, or conflicts with other software.
Issues with SettingsManagerData and RegRootHiveOverride

The log mentions problems with SettingsManagerData.get_RegRootHiveOverride(). This could indicate a problem with the Visual Studio settings or registry entries. It might be caused by a corrupted user profile, issues with the Windows registry, or problems with the specific Visual Studio installation.
VSIXInstaller.NoApplicableSKUsException: This extension is not installable on any currently installed products.

This error is quite straightforward. It means that the VSIX extension you're trying to install is not compatible with any of the Visual Studio versions installed on your machine. This could be due to version incompatibility or the extension being designed for a different product.
To troubleshoot and potentially resolve these issues, you can try the following steps:

Check Compatibility:

Ensure that the VSIX extension is compatible with the versions of Visual Studio installed on your system.
Run Visual Studio Installer:

Use the Visual Studio Installer to repair your Visual Studio installation. This can often resolve issues with corrupted installations or registry problems.
Run as Administrator:

Try running Visual Studio and the VSIX installer as an administrator. This can help if the issue is related to permissions.
Check for Conflicts:

Disable other extensions or add-ins to see if there is a conflict causing the issue.
Update Visual Studio:

Ensure that your Visual Studio installations are up to date. Sometimes, compatibility issues are fixed in updates.
Reinstall Visual Studio:

If none of the above steps work, consider reinstalling Visual Studio. This should be a last resort, as it's time-consuming and might disrupt your development environment.
Consult Documentation and Support:

Check the documentation for the VSIX extension for any specific installation requirements or known issues. Additionally, consider reaching out to the extension's developer or Visual Studio support for assistance.
Remember to back up your settings and important data before making significant changes to your development environment.

**Comment by AdaskoTheBeAsT** [comment] 2024-01-14 16:19
inactive issue - closing

**Closed by AdaskoTheBeAsT** 2024-01-14 16:19 UTC
